# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-28 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20170228_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prof',
            name='job',
        ),
        migrations.RemoveField(
            model_name='prof',
            name='location',
        ),
    ]
